server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_log
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      jdbc-url: ${DB_URL:jdbc:postgresql://localhost:5432/db_log}
      username: ${DB_LOGIN:postgres}
      password: ${DB_PASSWORD:root}
      schema: log_schema

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

#  sql:
#    init:
#      mode: always
#      data-locations: init/init-logs-tables.sql

#management:
#  endpoint:
#    loggers:
#      enabled: true
#
#  endpoints:
#    web:
#      exposure:
#        include: "health, info, loggers"